(define-module (gnu packages lsd)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system crate)
  #:use-module (guix licenses)

(define-public rust-lsd-0.23
  (package
    (name "rust-lsd")
    (version "0.23.1")
    (source (origin
              (method url-fetch)
              (uri (crate-uri "lsd" version))
              (file-name (string-append name "-" version ".tar.gz"))
              (sha256
               (base32
                "1v5p8fjrygiba8l1gazz8pi4hj4j5wdwysz8bqi6hph9i07vlxih"))))
    (build-system cargo-build-system)
    (arguments
     `(#:cargo-inputs (("rust-chrono" ,rust-chrono-0.4)
                       ("rust-chrono-humanize" ,rust-chrono-humanize-0.1)
                       ("rust-clap" ,rust-clap-3)
                       ("rust-clap" ,rust-clap-3)
                       ("rust-clap-complete" ,rust-clap-complete-3)
                       ("rust-crossterm" ,rust-crossterm-0.24)
                       ("rust-dirs" ,rust-dirs-3)
                       ("rust-globset" ,rust-globset-0.4)
                       ("rust-human-sort" ,rust-human-sort-0.2)
                       ("rust-libc" ,rust-libc-0.2)
                       ("rust-lscolors" ,rust-lscolors-0.9)
                       ("rust-serde" ,rust-serde-1)
                       ("rust-serde-yaml" ,rust-serde-yaml-0.8)
                       ("rust-term-grid" ,rust-term-grid-0.1)
                       ("rust-terminal-size" ,rust-terminal-size-0.1)
                       ("rust-unicode-width" ,rust-unicode-width-0.1)
                       ("rust-url" ,rust-url-2)
                       ("rust-users" ,rust-users-0.11)
                       ("rust-version-check" ,rust-version-check-0.9)
                       ("rust-wild" ,rust-wild-2)
                       ("rust-winapi" ,rust-winapi-0.3)
                       ("rust-xattr" ,rust-xattr-0.2)
                       ("rust-xdg" ,rust-xdg-2)
                       ("rust-yaml-rust" ,rust-yaml-rust-0.4))
       #:cargo-development-inputs (("rust-assert-cmd" ,rust-assert-cmd-1)
                                   ("rust-assert-fs" ,rust-assert-fs-1)
                                   ("rust-predicates" ,rust-predicates-1)
                                   ("rust-serial-test" ,rust-serial-test-0.5)
                                   ("rust-tempfile" ,rust-tempfile-3))))
    (home-page "https://github.com/Peltoche/lsd")
    (synopsis
     "An ls command with a lot of pretty colors and some other stuff.")
    (description
     "An ls command with a lot of pretty colors and some other stuff.")
    (license license:asl2.0)))

